User:
  name: Kevin_Dean
Saving:
  root_directory: C:\Users\MicroscopyInnovation\Desktop\Data
  save_directory: E://Kevin\Lung\MV3\GFP\2022-02-18\Cell000
  user: Kevin
  tissue: Lung
  celltype: MV3
  label: GFP
  file_type: TIFF
  date: 2022-06-07
  solvent: BABB
Devices:
  daq: NI
  camera: HamamatsuOrca
  etl: ETL
  filter_wheel: Sutter
  stage: PI
  zoom: Dynamixel
CameraParameters:
  number_of_cameras: 1
  x_pixels: 2048
  y_pixels: 2048
  sensor_mode: Normal
  readout_direction: Top to Bottom
  number_of_pixels: 10
  binning: 1x1
  pixel_size: 6.5
  frames_to_average: 1.0
  databuffer_size: 100
AutoFocusParameters:
  coarse_range: 500
  coarse_step_size: 50
  coarse_selected: True
  fine_range: 50
  fine_step_size: 5
  fine_selected: True
  robust_fit: True
StageParameters:
  xy_step: 500.0
  z_step: 500.0
  theta_step: 30.0
  f_step: 500.0
  x: 16000.0
  y: 53941.67
  z: 47100.0
  theta: 55.00006
  f: 66122.8
MicroscopeState:
  microscope_name: Mesoscale
  resolution_mode: Mesoscale
  image_mode: live
  zoom: 1x
  stack_cycling_mode: per_stack
  start_position: 0.0
  end_position: 200.0
  step_size: 0.2
  number_z_steps: 500.0
  timepoints: 1
  stack_pause: 0.0
  is_save: False
  stack_acq_time: 199.9999999999972
  timepoint_interval: 0
  experiment_duration: 600.0899999999995
  is_multiposition: False
  multipostion_count: 2
  selected_channels: 3
  channels: {'channel_1': {'is_selected': True, 'laser': '488nm', 'laser_index': 0, 'filter': 'GFP - FF01-515/30-32', 'filter_position': 1, 'camera_exposure_time': 200.0, 'laser_power': '20', 'interval_time': '1', 'defocus': 0.0}, 'channel_2': {'is_selected': True, 'laser': '562nm', 'laser_index': 1, 'filter': 'RFP - FF01-595/31-32', 'filter_position': 2, 'camera_exposure_time': 200.0, 'laser_power': '20', 'interval_time': '1', 'defocus': 0.0}, 'channel_3': {'is_selected': True, 'laser': '642nm', 'laser_index': 2, 'filter': 'Far-Red - BLP01-647R/31-32', 'filter_position': 3, 'camera_exposure_time': 200.0, 'laser_power': '20', 'interval_time': '1', 'defocus': 0.0}}
  stack_z_origin: 0
  stack_focus_origin: 0
  start_focus: 0.0
  end_focus: 0.0
  abs_z_start: 0.0
  abs_z_end: 200.0
  scanrange: 500.0
  n_plane: 1
  offset_start: 0.0
  offset_end: 10.0
  conpro_cycling_mode: Per Stack
  waveform_template: Default
MultiPositions:
  stage_positions: [{'x': 15000.0, 'y': 12000.0, 'z': 15500.0, 'theta': 0.0, 'f': 70000.0}, {'x': 35000.0, 'y': 42000.0, 'z': 15500.0, 'theta': 0.0, 'f': 70000.0}]
