User:
  name: Kevin_Dean
Saving:
  root_directory: E://
  save_directory: E://Kevin\Lung\MV3\GFP\2022-02-18\Cell000
  user: Kevin
  tissue: Lung
  celltype: MV3
  label: GFP
  date: 2022-02-18
Devices:
  daq: NI
  camera: HamamatsuOrca
  etl: ETL
  filter_wheel: Sutter
  stage: PI
  zoom: Dynamixel
CameraParameters:
  number_of_cameras: 1
  x_pixels: 512
  y_pixels: 512
  sensor_mode: Normal
  readout_direction: Top-to-Bottom
  number_of_pixels: 10
  binning: 1x1
  pixel_size: 6.5
  frames_to_average: 1
RemoteFocusParameters:
  remote_focus_l_delay_percent: 7.5
  remote_focus_l_ramp_rising_percent: 85
  remote_focus_l_ramp_falling_percent: 2.5
  remote_focus_l_amplitude: 0.7
  remote_focus_l_offset: 2.3
  remote_focus_r_delay_percent: 7.5
  remote_focus_r_ramp_rising_percent: 85
  remote_focus_r_ramp_falling_percent: 2.5
  remote_focus_r_amplitude: 0.7
  remote_focus_r_offset: 2.3
AutoFocusParameters:
  coarse_range: 500
  coarse_step_size: 50
  coarse_selected: True
  fine_range: 50
  fine_step_size: 5
  fine_selected: True
GalvoParameters:
  galvo_l_frequency: 99.9
  galvo_l_amplitude: 2.5
  galvo_l_offset: 0
  galvo_r_amplitude: 0.5
StageParameters:
  xy_step: 500.0
  z_step: 500.0
  theta_step: 30.0
  f_step: 500.0
  x: 35000.0
  y: 42000.0
  z: 15500.0
  theta: 0.0
  f: 70000.0
MicroscopeState:
  resolution_mode: low
  image_mode: single
  zoom: 1x
  stack_cycling_mode: per_stack
  start_position: 0.0
  end_position: 200.0
  step_size: 0.16
  number_z_steps: 1250.0
  timepoints: 1
  stack_pause: 0.0
  etl_amplitude: 0
  etl_offset: 0
  is_save: False
  stack_acq_time: 249.99999999999434
  timepoint_interval: 0
  experiment_duration: 625.090000000039
  is_multiposition: False
  channels: {'channel_1': {'is_selected': True, 'laser': '488nm', 'laser_index': 0, 'filter': 'GFP - FF01-515/30-32', 'filter_position': 1, 'camera_exposure_time': 200.0, 'laser_power': '75', 'interval_time': '1'}, 'channel_2': {'is_selected': True, 'laser': '488nm', 'laser_index': 0, 'filter': 'RFP - FF01-595/31-32', 'filter_position': 2, 'camera_exposure_time': 100.0, 'laser_power': '50', 'interval_time': '1'}, 'channel_3': {'is_selected': True, 'laser': '562nm', 'laser_index': 1, 'filter': 'RFP - FF01-595/31-32', 'filter_position': 2, 'camera_exposure_time': 200.0, 'laser_power': '50', 'interval_time': '1'}}
  stage_positions: {0: {'x': 15000.0, 'y': 12000.0, 'z': 15500.0, 'theta': 0.0, 'f': 70000.0}, 1: {'x': 35000.0, 'y': 42000.0, 'z': 15500.0, 'theta': 0.0, 'f': 70000.0}}
