{
  "Default": {
    "repeat": 1,
    "expand": 1,
  },
  "Confocal-Projection": {
    "repeat": timepoints,
    "expand": n_plane,
  },
    "Bidirectional": {
      "repeat": 1,
      "expand": 2,
    }
}